numero_um = input("Informe um numero 1: ")
numero_dois = input("Informe o numero 2: ")
comparasão_um= int(numero_um) > int(numero_dois)
comparasão_dois= int(numero_um) < int(numero_dois)
comparasão_tres = int(numero_um) >= int(numero_dois)
comparasão_quatro= int(numero_um) <= int(numero_dois)
print(f"Comparação um, o numero 1 e maior que o numero 2: {comparasão_um} ")
print(f"Comparação dois, o numero 2 e maior que o numero 1:  {comparasão_dois}")
print(f"Comparação tres, o numero 1 e maior ou igual numero 2: {comparasão_tres} ")
print(f"Comparação quatro, o numero 2 e maior ou igual numero 1: {comparasão_quatro} ")
